baseurl = "https://www.thealphasguide.com/"
title = "銀河カプセラガイド"
languageCode = "ja-jp"

theme = "hugo-theme-learn"
publishdir = "public"
builddrafts = true

[params]
  menu = [
    "start",
    "rookie-fitting",
    "market",
    "career-agents",
    "upgrading-ships",
    "new-goals",
    "training",
    "corps",
    "learn-more",
    "reference"
  ]
  editURL = "https://github.com/ayust/alpha-guide/edit/master/content/"
